alias q="exit"
alias c="clear"
alias h="history"
alias t="time"
alias null="/dev/null"

alias home="cd ~"
alias root="cd /"
alias ..="cd .."
alias ..."=cd ..; cd .."
alias ....="cd ..; cd ..; cd.."

alias g="git"
alias gst="git status"
alias gcom="git commit -m"
alias gclone="git clone"
alias gsth="git stash"
alias glg="git log"
alias gall="git all ."
